### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by rothos** [carderne/signal-export#117]
**Desktop (please complete the following information):**
 - OS and version: Mac OS Sonoma 14.0
- Terminal/shell used: zsh

**Describe the bug**
I successfully installed the package via pip3. When I try to run it, this happens:
```
❯ sigexport ./2024-03-26
Traceback (most recent call last):
  File "/Users/gar/Library/Python/3.9/bin/sigexport", line 5, in <module>
    from sigexport.main import cli
  File "/Users/gar/Library/Python/3.9/lib/python/site-packages/sigexport/main.py", line 13, in <module>
    from sigexport import __version__, create, files, html, logging, merge, models, utils
  File "/Users/gar/Library/Python/3.9/lib/python/site-packages/sigexport/create.py", line 3, in <module>
    from sigexport import models, utils
  File "/Users/gar/Library/Python/3.9/lib/python/site-packages/sigexport/models.py", line 10, in <module>
    class RawMessage:
  File "/Users/gar/Library/Python/3.9/lib/python/site-packages/sigexport/models.py", line 15, in RawMessage
    type: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

Any idea what's going on here? I searched and didn't find this error in any previous bug reports.

**Comment by carderne** [comment]
Should be fixed by https://github.com/carderne/signal-export/commit/60c11ad809bd490bded3d3d5270940882bdd9bd0, released in latest version.

Do `pip install signal-export>=2.2.2` and try again!

**Comment by rothos** [comment]
It worked. Thank you Chris!
