### ISSUE TITLE
KeyError: 'sent_at'

### ISSUE THREAD

**Issue by ProactiveServices** [carderne/signal-export#22]
Using script as at 23rd June 12:19, Python 3.8.5 on Kubuntu 20.01. Running against Signal Beta 5.6.0-beta1. Chugs through a lot of conversations then returns:

Traceback (most recent call last):
  File "./sigexport.py", line 104, in make_simple
    timestamp = msg["timestamp"]
KeyError: 'timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./sigexport.py", line 615, in <module>
    main()
  File "/src/third-party/signal-export/signal-export/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/src/third-party/signal-export/signal-export/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/src/third-party/signal-export/signal-export/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/src/third-party/signal-export/signal-export/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "./sigexport.py", line 601, in main
    make_simple(dest, convos, contacts)
  File "./sigexport.py", line 107, in make_simple
    timestamp = msg["sent_at"]
KeyError: 'sent_at'

**Comment by carderne** [comment]
Check the commit I just pushed, should fix it: 1d0ffb513744ef7dda228f2d6927fd0abfdbedfb

**Comment by ProactiveServices** [comment]
That was quick - works a charm! Thank you very much.
