### ISSUE TITLE
sqlite3.OperationalError: malformed database schema (messages) - near "AS": syntax error

### ISSUE THREAD

**Issue by berrytsakala** [carderne/signal-export#26]
```
~/downloads/signal-export  $ ./sigexport.py --manual exports/
ok

Traceback (most recent call last):
  File "./sigexport.py", line 621, in <module>
    main()
  File "/home/dy/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dy/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dy/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dy/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "./sigexport.py", line 585, in main
    convos, contacts = fetch_data(db_file, key, manual=manual, chats=chats)
  File "./sigexport.py", line 217, in fetch_data
    c.execute(query)
sqlite3.OperationalError: malformed database schema (messages) - near "AS": syntax error
```

what have i done to deserve this:
====================

- downloaded signal-export just now, 2021-08-07, 
- followed the install instructions from the readme, 
- compiled without problems
- had to add the --manual argument ;
- received the above error.

my setup:
=======

- signal 5.11.0
- mx linux 
- uname -a:  5.10.0-5mx-amd64 #1 SMP Debian 5.10.26-1~mx19+1 (2021-04-01) x86_64

thanks.

**Comment by carderne** [comment]
Hi @berrytsakala, are you comfortable to try opening the decrypted database in another SQLite browser and see if you're able to query that way?

**Comment by franklin-be** [comment]
I'm on android as well.

**Comment by coletonodonnell** [comment]
@franklin-be did it work or did you get a similar error?

**Comment by franklin-be** [comment]
export generally works. Only have issues with received media lately as stated here: https://github.com/carderne/signal-export/issues/28

**Comment by haarp** [comment]
@coletonodonnell
Did you ever manage to solve this? Also on Gentoo here, getting the exact same errors when trying to dump Desktop client's db. I wonder if the Gentoo ebuild compiles sqlcipher differently...

**Comment by haarp** [comment]
Solved it.

Problem 1: `Error: file is not a database`: sqlcipher can't decrypt the database. Usually because the key is entered with wrong syntax. The proper syntax is: `pragma key = "x'abc123abc123'";`.

Problem 2: `malformed database schema (messages) - near "AS": syntax error`: sqlcipher is too old. Version 4.0.1 spits out this error, version 4.5.0 worked.

**Comment by coletonodonnell** [comment]
Sweet, great work. Are you running Apple or Android? I haven't looked at the old issue too hard but iirc we thought it could've been a problem with Apple vs. Android.

**Comment by carderne** [comment]
@haarp I haven't quite followed the discussion here but is there a PR you could submit?

**Comment by haarp** [comment]
> @haarp I haven't quite followed the discussion here but is there a PR you could submit?

Good idea. #53

**Comment by carderne** [comment]
Thanks! And the `pragma key = ...` syntax? I assume that was just entering it incorrectly when trying to decrypt in the command line?

**Comment by haarp** [comment]
Yes, that's probably the problem. I discovered this while messing around on the commandline, and presumably @coletonodonnell did too. Syntax looks to be correct inthe script: https://github.com/carderne/signal-export/blob/8e119b1dbaa5e59312fd830f2252763092e61de9/sigexport.py#L190

I must admit I haven't used this script, just found this issue on Google trying to use sqlcipher on Signal :)

**Comment by carderne** [comment]
:P well thanks for your contribution!
