### ISSUE TITLE
ModuleNotFoundError: No module named 'sigexport'

### ISSUE THREAD

**Issue by elkrojo** [carderne/signal-export#36]
$ sigexport /Users/userid/Desktop/sigexport
Traceback (most recent call last):
  File "/usr/local/bin/sigexport", line 5, in <module>
    from sigexport.main import cli
ModuleNotFoundError: No module named 'sigexport'

I can find the sigexport executable but I can't find where the files of sigexport module are installed.

Can you point me in the right direction?
I followed the steps for mac os installation and i'm running monterey.

**Comment by vinnytroia** [comment]
Same issue. actually, i just get "command not found". I suspect you are further along in the install process than i am. i was able to install it without a problem though. Where are you finding the executable?

when i run the install again, i get this: 
Requirement already satisfied: click<7.2.0,>=7.1.1 in ./Library/Python/3.8/lib/python/site-packages (from typer<0.4.0,>=0.3.0->typer-cli>=0.0.12->signal-export==1.0.0) (7.1.2)

i cant get the file to execute. any thoughts on where it should be? i am also running monterray.

**Comment by vinnytroia** [comment]
Update. I installed miniconda and python3.6 to get a clean python environment. Now i'm getting the same error as @elkrojo - no module named 'sigexport'

**Comment by carderne** [comment]
Should be fixed by acf8fdf728926adf3ac8202bb4e77b4df2b4f53a

Let me know!

**Comment by vinnytroia** [comment]
Getting closer. Index out of range now. This happens both with and without parameters. using it with --help works though


Copying and renaming attachments
Traceback (most recent call last):
  File "/Users/sysop/opt/miniconda3/bin/sigexport", line 8, in <module>
    sys.exit(cli())
  File "/Users/sysop/opt/miniconda3/lib/python3.6/site-packages/sigexport/main.py", line 613, in cli
    run(main)
  File "/Users/sysop/opt/miniconda3/lib/python3.6/site-packages/typer/main.py", line 859, in run
    app()
  File "/Users/sysop/opt/miniconda3/lib/python3.6/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/sysop/opt/miniconda3/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sysop/opt/miniconda3/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/sysop/opt/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sysop/opt/miniconda3/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/sysop/opt/miniconda3/lib/python3.6/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/sysop/opt/miniconda3/lib/python3.6/site-packages/sigexport/main.py", line 597, in main
    copy_attachments(src, dest, convos, contacts)
  File "/Users/sysop/opt/miniconda3/lib/python3.6/site-packages/sigexport/main.py", line 66, in copy_attachments
    file_name += "." + att["contentType"].split("/")[1]
IndexError: list index out of range

**Comment by vinnytroia** [comment]
It worked with an individual chat export, so it must be a problem with one of the chats.

**Comment by carderne** [comment]
Flip their storage schema is a bit of a moving target...

Could you a print statement as follows (without the `+` symbold) just before line 66 that errored:
```diff
+ print(att["contentType"])
file_name += "." + att["contentType"].split("/")[1]
```
And then run it with `--verbose`, e.g. `sigexport --verbose`.

And share the last output just before it errors. They're supposed to look like `image/png` or `audio/mp3`, but you found one that is either blank or doesn't have a `/` in it...

**Comment by elkrojo** [comment]
Okay. Working beautifully now.

Thanks.
