### ISSUE TITLE
Question of a newbie about environment variables

### ISSUE THREAD

**Issue by hoeks029** [carderne/signal-export#47]
I am very new at this and wonder how/where to "Then set your input and output locations as environment variables."? I have installed Docker and the Dockerfile and can run Docker in the command prompt. Help appreciated!

**Comment by carderne** [comment]
It means run the lines under that text in a command line.

Assuming you’re on Windows, run the following in command prompt, hitting enter between each line.

```
SIGNAL_INPUT="~/AppData/Roaming/Signal"

SIGNAL_OUTPUT="~/Documents/output"
```

And then run the `docker run …` command from the main README.

**Comment by hoeks029** [comment]
Thanks for your reply! In my command prompt this leads to this error message:
'SIGNAL_INPUT' is not recognized as an internal or external command,
operable program or batch file.
Obviously I am making some (silly) mistake.

**Comment by carderne** [comment]
Sorry, I don’t use Windows…

Forget about the environment variables and try running this (should output to your Downloads folder):

```
docker run --rm -it --name signal-export -v %USERPROFILE%/AppData/Roaming/Signal:/Signal -v %USERPROFILE%/Downloads/SignalExport:/output carderne/signal-export:latest
```

**Comment by hoeks029** [comment]
Thank you so much, it worked! (In replies the original message is not shown, but everything else is really perfect, including pictures, audio and emoji!) You really helped me out here.

**Comment by carderne** [comment]
@hoeks029 add `—quote` to the end of the long command I provided above to get quoted messages.

**Comment by hoeks029** [comment]
Thanks for the reply!
Unfortunately this leads to an unexpected ending (see below), but this is probably not something you can fix?

Traceback (most recent call last):
 File "/usr/local/bin/sigexport", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 647, in cli
    run(main)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 864, in run
    app()
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 634, in main
    make_simple(dest, convos, contacts, quote)
  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 201, in make_simple
    quote += msg["quote"]["text"]
TypeError: can only concatenate str (not "NoneType") to str

**Comment by carderne** [comment]
Hi @hoeks029, sorry for the delay, work/travel. This should be fixed now. I haven't worked with the quote code much so it's probably still a bit shaky...

**Comment by carderne** [comment]
Please open a new issue if you have more problems with this!
