### ISSUE TITLE
Contacts with special characters in the name like "()" break the export process even if escaped

### ISSUE THREAD

**Issue by chain-enterprises** [carderne/signal-export#60]
This is on the latest Docker image as of:  18 Mar 2022

________________________________________________________________

Traceback (most recent call last):
  File "/usr/local/bin/sigexport", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 652, in cli
    run(main)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 864, in run
    app()
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 637, in main
    copy_attachments(src, dest, convos, contacts)
  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 70, in copy_attachments
    file_name += "." + att["contentType"].split("/")[1]
IndexError: list index out of range

**Comment by carderne** [comment]
Your issue title doesn't match the traceback that you posted...

The latter should now be fixed by https://github.com/carderne/signal-export/commit/743e4ba149ce2261e511b2445d7637bcd2773a54

(You may need to wait for the images to rebuild, and add `--pull=always` to your `docker run`.)

**Comment by chain-enterprises** [comment]
I realized the error was from elsewhere after I posted 

Thank you
