### ISSUE TITLE
Docker on Windows: cannot import name 'get_terminal_size' from 'click.termui'

### ISSUE THREAD

**Issue by T0BiD** [carderne/signal-export#62]
Hi, tried running this with docker on a windows machine, but starting the container fails to the following error:

```
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/usr/local/lib/python3.9/site-packages/click/termui.py)

Traceback (most recent call last):

  File "/usr/local/bin/sigexport", line 5, in <module>

    from sigexport.main import cli

  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 12, in <module>

    from typer import run, secho, Option, Argument, colors

  File "/usr/local/lib/python3.9/site-packages/typer/__init__.py", line 12, in <module>

    from click.termui import get_terminal_size as get_terminal_size

ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/usr/local/lib/python3.9/site-packages/click/termui.py)
```

**Comment by carderne** [comment]
Fixed by https://github.com/carderne/signal-export/commit/65bada89b60385081ca5d851a389ac7dde8999c9.

Make sure to run the image with `docker run --pull=always` so you get the update.
